-- =============================================================================
-- dryrun.sql  --  PLAN step 4.1: build everything in wrapt, check it, roll back
--
-- GENERATED by `python migration/stage3/loadgen.py static` from
-- supabase/migrations/001-004. Don't edit by hand; edit the migrations and
-- regenerate.
--
-- RUN IN:     wrapt's Supabase project -> SQL Editor -> paste all -> Run.
-- WHAT:       ONE `do` block: a clash check, then 001, 002, 003 and 004 verbatim
--             (each via EXECUTE), then catalogue checks. It always ends by
--             raising an exception, and a single statement is atomic, so
--             NOTHING persists — no schema, no grants, no publication change.
--             Does not need pg_net (003 no-ops without it).
-- EXPECTED:   an ERROR whose text starts
--               DRY RUN OK (all rolled back): tables=5 policies=13 functions=5 ...
--             "DRY RUN ABORTED" = schema yumlog already exists (nothing done).
--             "DRY RUN FAILED"  = a check failed; the text lists which.
--             Any other error   = a real problem in the migration SQL: copy the
--                                 message (and line number) back.
-- THEN:       run  select to_regnamespace('yumlog');   on its own. It must
--             return NULL (proves the rollback; PLAN Q1).
-- =============================================================================
do $dryrun$
declare
  problems text := '';
  summary  text := '';
  n        bigint;
  t        text;
begin
  if to_regnamespace('yumlog') is not null then
    raise exception 'DRY RUN ABORTED: schema yumlog already exists in this project, so a dry run can''t prove anything. Nothing was changed.';
  end if;

  -- ===== supabase/migrations/001_yumlog_schema.sql (verbatim) =====
  execute $m001$
-- =============================================================================
-- 001_yumlog_schema.sql  --  yumlog schema, tables, constraints, FK indexes,
--                            members allowlist, shopping_list updated_at trigger
--
-- PURPOSE:    Yumlog's data lives in its own `yumlog` schema inside wrapt's
--             Supabase project (see CLAUDE.md "Database schema"). This file
--             creates the objects only; who may touch them is 002.
--             Tables, columns (incl. column order), defaults, identity, the
--             category CHECK and the FKs match the old yumlog project's live
--             `public` schema exactly (migration/stage1 facts, 2026-09-28),
--             with the FKs repointed at yumlog.*. New vs the old project:
--             three FK indexes and yumlog.members.
-- RUN IN:     wrapt's Supabase project -> SQL Editor -> New query -> paste all -> Run.
--             Run order: 001 -> 002 -> 003 -> 004 (005 is optional).
-- IDEMPOTENT: yes. `if not exists` / `create or replace` / drop-then-create
--             throughout; safe to re-run. It never alters an existing table's
--             columns, so re-running is not a way to change them.
-- RESULT:     the last statement is a verification SELECT (one grid). Every row
--             should read status = OK.
-- ROLLBACK:   drop schema yumlog cascade;   (destroys all yumlog data)
-- =============================================================================

create schema if not exists yumlog;

-- Postgres grants EXECUTE on every new function to PUBLIC. Supabase's usual
-- schema-level default ACLs exist only for `public`, so nothing else is
-- granted by accident here. Note: per the ALTER DEFAULT PRIVILEGES docs, a
-- per-schema REVOKE cannot remove the built-in global PUBLIC default, so this
-- line alone does not stop PUBLIC getting EXECUTE — the explicit REVOKEs after
-- each function (here, 002 and 003) do that, and the verification SELECTs
-- prove it. Kept as the documented intent, and harmless.
alter default privileges for role postgres in schema yumlog
  revoke execute on functions from public;

-- ---------------------------------------------------------------------------
-- Tables (FK order: ingredients, recipes, recipe_ingredients, shopping_list)
-- ---------------------------------------------------------------------------

-- Canonical ingredient registry (one row per normalised name).
create table if not exists yumlog.ingredients (
  name      text not null,
  category  text,              -- shopping-list aisle; null = valid in recipes but not shopped
  constraint ingredients_pkey primary key (name),
  constraint ingredients_category_check check (
    category is null or category = any (array[
      'fresh produce'::text, 'fridge'::text, 'freezer'::text, 'snacks'::text,
      'baking'::text, 'international food'::text, 'breakfast'::text, 'drinks'::text,
      'spices'::text, 'tinned'::text, 'other pantry'::text
    ])
  )
);

-- Recipes, keyed by a readable slug. Column order matches the old project
-- (tips / substitutions / updated_at were added later, hence their position).
create table if not exists yumlog.recipes (
  slug           text not null,
  title          text not null,
  category       text,
  protein        text,
  cook_time_min  integer,
  method         text not null,
  source_url     text,
  created_at     timestamptz default now(),
  tips           text,
  substitutions  text,
  updated_at     timestamptz not null default now(),   -- bumped to trigger rebuilds (003)
  constraint recipes_pkey primary key (slug)
);

-- Per-recipe ingredient lines.
create table if not exists yumlog.recipe_ingredients (
  id            bigint generated always as identity,
  recipe_slug   text not null,
  ingredient    text not null,
  display_name  text,
  quantity      numeric,
  unit          text,
  constraint recipe_ingredients_pkey primary key (id),
  constraint recipe_ingredients_recipe_slug_fkey foreign key (recipe_slug)
    references yumlog.recipes (slug) on delete cascade,
  constraint recipe_ingredients_ingredient_fkey foreign key (ingredient)
    references yumlog.ingredients (name) on update cascade on delete restrict
);

-- The single shared shopping list.
create table if not exists yumlog.shopping_list (
  id          bigint generated always as identity,
  ingredient  text not null,
  quantity    numeric,
  unit        text,
  checked     boolean not null default false,
  position    integer,
  added_at    timestamptz default now(),
  updated_at  timestamptz not null default now(),
  constraint shopping_list_pkey primary key (id),
  constraint shopping_list_ingredient_fkey foreign key (ingredient)
    references yumlog.ingredients (name) on update cascade on delete restrict
);

-- FK indexes (none existed in the old project). Cascades on rename and the
-- per-recipe ingredient reads both use them.
create index if not exists recipe_ingredients_recipe_slug_idx on yumlog.recipe_ingredients (recipe_slug);
create index if not exists recipe_ingredients_ingredient_idx  on yumlog.recipe_ingredients (ingredient);
create index if not exists shopping_list_ingredient_idx       on yumlog.shopping_list (ingredient);

-- Who may write. Wrapt has public sign-ups, so "authenticated" is not enough;
-- only auth users listed here are yumlog members (see 002 is_member()).
-- RLS on with NO policies and (002) NO grants: only postgres can read or
-- change it, via the SQL editor.
create table if not exists yumlog.members (
  user_id   uuid not null,
  note      text,
  added_at  timestamptz not null default now(),
  constraint members_pkey primary key (user_id),
  constraint members_user_id_fkey foreign key (user_id)
    references auth.users (id) on delete cascade
);

alter table yumlog.ingredients        enable row level security;
alter table yumlog.recipes            enable row level security;
alter table yumlog.recipe_ingredients enable row level security;
alter table yumlog.shopping_list      enable row level security;
alter table yumlog.members            enable row level security;

-- ---------------------------------------------------------------------------
-- shopping_list.updated_at auto-touch (drives "Shopping list last changed")
-- ---------------------------------------------------------------------------

create or replace function yumlog.shopping_list_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- Trigger-only: nobody needs to call it directly (EXECUTE isn't checked when
-- a trigger fires).
revoke execute on function yumlog.shopping_list_set_updated_at() from public, anon, authenticated, service_role;

drop trigger if exists shopping_list_set_updated_at on yumlog.shopping_list;
create trigger shopping_list_set_updated_at
  before update on yumlog.shopping_list
  for each row execute function yumlog.shopping_list_set_updated_at();

notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- Verification (the grid the editor shows). Every row: status = OK.
-- ---------------------------------------------------------------------------
with
expected_cols(tbl, cols) as (
  values
    ('ingredients',        'name text NOT NULL | category text NULL'),
    ('recipes',            'slug text NOT NULL | title text NOT NULL | category text NULL | protein text NULL | cook_time_min integer NULL | method text NOT NULL | source_url text NULL | created_at timestamp with time zone NULL DEFAULT now() | tips text NULL | substitutions text NULL | updated_at timestamp with time zone NOT NULL DEFAULT now()'),
    ('recipe_ingredients', 'id bigint NOT NULL IDENTITY ALWAYS | recipe_slug text NOT NULL | ingredient text NOT NULL | display_name text NULL | quantity numeric NULL | unit text NULL'),
    ('shopping_list',      'id bigint NOT NULL IDENTITY ALWAYS | ingredient text NOT NULL | quantity numeric NULL | unit text NULL | checked boolean NOT NULL DEFAULT false | position integer NULL | added_at timestamp with time zone NULL DEFAULT now() | updated_at timestamp with time zone NOT NULL DEFAULT now()'),
    ('members',            'user_id uuid NOT NULL | note text NULL | added_at timestamp with time zone NOT NULL DEFAULT now()')
),
actual_cols as (
  select c.relname::text as tbl,
         string_agg(
           a.attname || ' ' || format_type(a.atttypid, a.atttypmod)
           || case when a.attnotnull then ' NOT NULL' else ' NULL' end
           || coalesce(' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid), '')
           || case a.attidentity when 'a' then ' IDENTITY ALWAYS' when 'd' then ' IDENTITY BY DEFAULT' else '' end,
           ' | ' order by a.attnum) as cols
  from pg_class c
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
  where c.relnamespace = to_regnamespace('yumlog') and c.relkind = 'r'
  group by c.relname
),
expected_cons(name, def) as (
  values
    ('ingredients.ingredients_pkey',                           'PRIMARY KEY (name)'),
    ('ingredients.ingredients_category_check',                 'CHECK (category IS NULL OR (category = ANY (ARRAY[''fresh produce''::text, ''fridge''::text, ''freezer''::text, ''snacks''::text, ''baking''::text, ''international food''::text, ''breakfast''::text, ''drinks''::text, ''spices''::text, ''tinned''::text, ''other pantry''::text])))'),
    ('recipes.recipes_pkey',                                   'PRIMARY KEY (slug)'),
    ('recipe_ingredients.recipe_ingredients_pkey',             'PRIMARY KEY (id)'),
    ('recipe_ingredients.recipe_ingredients_recipe_slug_fkey', 'FOREIGN KEY (recipe_slug) REFERENCES yumlog.recipes(slug) ON DELETE CASCADE'),
    ('recipe_ingredients.recipe_ingredients_ingredient_fkey',  'FOREIGN KEY (ingredient) REFERENCES yumlog.ingredients(name) ON UPDATE CASCADE ON DELETE RESTRICT'),
    ('shopping_list.shopping_list_pkey',                       'PRIMARY KEY (id)'),
    ('shopping_list.shopping_list_ingredient_fkey',            'FOREIGN KEY (ingredient) REFERENCES yumlog.ingredients(name) ON UPDATE CASCADE ON DELETE RESTRICT'),
    ('members.members_pkey',                                   'PRIMARY KEY (user_id)'),
    ('members.members_user_id_fkey',                           'FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE')
),
report(ord, item, expected, actual) as (
  select 1, 'schema yumlog exists', 'true', (to_regnamespace('yumlog') is not null)::text
  union all
  select 2, 'schema owner', 'postgres',
         coalesce((select pg_get_userbyid(n.nspowner)::text from pg_namespace n where n.nspname = 'yumlog'), '<none>')
  -- columns, in order, per table (pg_get_constraintdef qualifies names outside
  -- the search_path, so FKs read yumlog.* / auth.* below)
  union all
  select 10, 'columns ' || e.tbl, e.cols, coalesce(a.cols, '<table missing>')
  from expected_cols e left join actual_cols a on a.tbl = e.tbl
  union all
  select 20, 'constraint ' || e.name, e.def,
         coalesce((select pg_get_constraintdef(co.oid, true)
                   from pg_constraint co
                   where co.conrelid = to_regclass('yumlog.' || split_part(e.name, '.', 1))
                     and co.conname = split_part(e.name, '.', 2)), '<missing>')
  from expected_cons e
  union all
  select 30, 'constraint count (all 5 tables)', '10',
         (select count(*) from pg_constraint co
          join pg_class c on c.oid = co.conrelid
          where c.relnamespace = to_regnamespace('yumlog')
            and co.contype in ('p', 'f', 'c', 'u'))::text
  union all
  select 40, 'index ' || i.idx, 'present',
         case when to_regclass('yumlog.' || i.idx) is null then '<missing>' else 'present' end
  from (values ('recipe_ingredients_recipe_slug_idx'), ('recipe_ingredients_ingredient_idx'),
               ('shopping_list_ingredient_idx')) as i(idx)
  union all
  select 50, 'RLS enabled ' || c.relname, 'true', c.relrowsecurity::text
  from pg_class c
  where c.relnamespace = to_regnamespace('yumlog') and c.relkind = 'r'
  union all
  select 60, 'identity sequence ' || s.seq, 'present',
         case when to_regclass('yumlog.' || s.seq) is null then '<missing>' else 'present' end
  from (values ('recipe_ingredients_id_seq'), ('shopping_list_id_seq')) as s(seq)
  union all
  select 70, 'trigger shopping_list_set_updated_at', 'BEFORE UPDATE FOR EACH ROW',
         coalesce((select case when (tg.tgtype & 2) <> 0 then 'BEFORE' else 'AFTER' end
                          || case when (tg.tgtype & 16) <> 0 then ' UPDATE' else ' <not update>' end
                          || case when (tg.tgtype & 1) <> 0 then ' FOR EACH ROW' else ' FOR EACH STATEMENT' end
                   from pg_trigger tg
                   where tg.tgrelid = to_regclass('yumlog.shopping_list')
                     and tg.tgname = 'shopping_list_set_updated_at'), '<missing>')
  union all
  select 80, 'fn shopping_list_set_updated_at: definer / search_path', 'false / search_path=""',
         coalesce((select p.prosecdef::text || ' / ' || coalesce(array_to_string(p.proconfig, ','), '<none>')
                   from pg_proc p
                   where p.oid = to_regprocedure('yumlog.shopping_list_set_updated_at()')), '<missing>')
  union all
  select 81, 'fn shopping_list_set_updated_at: EXECUTE public/anon/authenticated/service_role',
         'false/false/false/false',
         coalesce((select has_function_privilege('public', p.oid, 'EXECUTE')::text
                          || '/' || has_function_privilege('anon', p.oid, 'EXECUTE')::text
                          || '/' || has_function_privilege('authenticated', p.oid, 'EXECUTE')::text
                          || '/' || has_function_privilege('service_role', p.oid, 'EXECUTE')::text
                   from pg_proc p
                   where p.oid = to_regprocedure('yumlog.shopping_list_set_updated_at()')), '<missing>')
)
select ord, item, expected, actual,
       case when expected = actual then 'OK' else 'MISMATCH' end as status
from report
order by ord, item;

$m001$;

  -- ===== supabase/migrations/002_yumlog_security.sql (verbatim) =====
  execute $m002$
-- =============================================================================
-- 002_yumlog_security.sql  --  grants, is_member(), RLS policies, RPCs
--
-- PURPOSE:    Who may read and write yumlog.*. Wrapt has public sign-ups, so
--             "authenticated" is NOT "Tim or Zoe": every write, every
--             shopping-list read and both RPCs are gated on yumlog.members via
--             yumlog.is_member(). Grants are explicit and exact (see the matrix
--             in the verification SELECT):
--               anon           USAGE on schema; SELECT on recipes, ingredients,
--                              recipe_ingredients. Nothing else.
--               authenticated  USAGE; SELECT/INSERT/UPDATE/DELETE on the four
--                              app tables (RLS decides which rows); EXECUTE on
--                              is_member + the two RPCs.
--               service_role   NOTHING — not even schema USAGE. Wrapt's /ask
--                              runs model SQL as service_role; without USAGE it
--                              gets "permission denied for schema yumlog".
--               PUBLIC         nothing.
--             merge_ingredients / touch_recipes_for_ingredient are SECURITY
--             INVOKER now (they were DEFINER in the old project): a member
--             passes RLS on every table they touch, so definer rights bought
--             nothing but risk. The member guard gives a clear error instead of
--             silently updating 0 rows.
-- RUN IN:     wrapt's Supabase project, after 001.
-- IDEMPOTENT: yes. Grants are reset (revoke all, then grant exactly) on every
--             run; policies are drop-if-exists then create; functions are
--             create or replace.
-- RESULT:     verification SELECT; every row status = OK.
-- ROLLBACK:   drop schema yumlog cascade;  (or re-run after editing)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema, table and sequence grants (reset, then grant exactly)
-- ---------------------------------------------------------------------------

revoke all on schema yumlog from public, anon, authenticated, service_role;
grant usage on schema yumlog to anon, authenticated;

revoke all on all tables in schema yumlog from public, anon, authenticated, service_role;
grant select on yumlog.recipes, yumlog.ingredients, yumlog.recipe_ingredients to anon;
grant select, insert, update, delete
  on yumlog.recipes, yumlog.ingredients, yumlog.recipe_ingredients, yumlog.shopping_list
  to authenticated;
-- yumlog.members: no grants to anyone (postgres owns it).

-- Identity inserts shouldn't need sequence rights, but it's cheap insurance.
revoke all on all sequences in schema yumlog from public, anon, authenticated, service_role;
grant usage, select on sequence yumlog.recipe_ingredients_id_seq, yumlog.shopping_list_id_seq
  to authenticated;

-- ---------------------------------------------------------------------------
-- is_member(): the allowlist check every write policy and RPC uses
-- ---------------------------------------------------------------------------

-- SECURITY DEFINER so it can read yumlog.members, which nobody else can.
-- Read-only, returns a boolean about the caller only.
create or replace function yumlog.is_member()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from yumlog.members m where m.user_id = (select auth.uid())
  );
$$;

-- ---------------------------------------------------------------------------
-- RPCs (called by src/lib/ingredient-registry.ts)
-- ---------------------------------------------------------------------------

-- Bump recipes.updated_at on every recipe using an ingredient, so the
-- recipes rebuild trigger (003) redeploys the static pages after a rename.
create or replace function yumlog.touch_recipes_for_ingredient(p_ingredient text)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  touched integer;
begin
  if not yumlog.is_member() then
    raise exception 'not a yumlog member' using errcode = '42501';
  end if;

  update yumlog.recipes r
  set updated_at = now()
  from yumlog.recipe_ingredients ri
  where ri.recipe_slug = r.slug
    and ri.ingredient = p_ingredient;

  get diagnostics touched = row_count;
  return touched;
end;
$$;

-- Merge p_source into p_target: repoint recipe lines, merge shopping rows by
-- unit, delete the source name, then touch affected recipes. Body ported
-- unchanged from the old project's public.merge_ingredients (formerly
-- scripts/ingredient-registry-rpc.sql, see git history), apart from the
-- member guard, SECURITY INVOKER and fully qualified names.
create or replace function yumlog.merge_ingredients(p_source text, p_target text)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  r record;
  match_id bigint;
  match_qty numeric;
  merged_recipe_lines integer;
  merged_list_rows integer;
begin
  if not yumlog.is_member() then
    raise exception 'not a yumlog member' using errcode = '42501';
  end if;

  if p_source = p_target then
    raise exception 'Cannot merge an ingredient into itself';
  end if;

  if not exists (select 1 from yumlog.ingredients where name = p_source) then
    raise exception 'Source ingredient not found';
  end if;

  if not exists (select 1 from yumlog.ingredients where name = p_target) then
    raise exception 'Target ingredient not found';
  end if;

  select count(*)::int into merged_recipe_lines
  from yumlog.recipe_ingredients where ingredient = p_source;

  select count(*)::int into merged_list_rows
  from yumlog.shopping_list where ingredient = p_source;

  update yumlog.recipe_ingredients
  set ingredient = p_target
  where ingredient = p_source;

  for r in
    select id, unit, quantity from yumlog.shopping_list where ingredient = p_source
  loop
    select sl.id, sl.quantity
    into match_id, match_qty
    from yumlog.shopping_list sl
    where sl.ingredient = p_target
      and sl.unit is not distinct from r.unit
    limit 1;

    if match_id is not null then
      update yumlog.shopping_list
      set quantity = coalesce(match_qty, 0) + coalesce(r.quantity, 0)
      where id = match_id;
      delete from yumlog.shopping_list where id = r.id;
    else
      update yumlog.shopping_list set ingredient = p_target where id = r.id;
    end if;
  end loop;

  delete from yumlog.ingredients where name = p_source;

  perform yumlog.touch_recipes_for_ingredient(p_target);

  return jsonb_build_object(
    'recipe_lines', merged_recipe_lines,
    'shopping_list_rows', merged_list_rows
  );
end;
$$;

-- Postgres gives PUBLIC EXECUTE on every new function; take it away from
-- everyone, then grant back only what the app needs. (003's trigger
-- function repeats this for itself.)
revoke execute on all functions in schema yumlog from public, anon, authenticated, service_role;
grant execute on function
  yumlog.is_member(),
  yumlog.merge_ingredients(text, text),
  yumlog.touch_recipes_for_ingredient(text)
  to authenticated;

-- ---------------------------------------------------------------------------
-- RLS policies. Per-command on the three public tables (one public SELECT
-- policy, member-only writes — no overlapping permissive SELECTs); one
-- FOR ALL policy on shopping_list, which has a single audience.
-- `(select yumlog.is_member())` is evaluated once per statement, not per row.
-- ---------------------------------------------------------------------------

-- recipes
drop policy if exists "recipes public read" on yumlog.recipes;
create policy "recipes public read" on yumlog.recipes
  for select to anon, authenticated using (true);
drop policy if exists "recipes member insert" on yumlog.recipes;
create policy "recipes member insert" on yumlog.recipes
  for insert to authenticated with check ((select yumlog.is_member()));
drop policy if exists "recipes member update" on yumlog.recipes;
create policy "recipes member update" on yumlog.recipes
  for update to authenticated
  using ((select yumlog.is_member())) with check ((select yumlog.is_member()));
drop policy if exists "recipes member delete" on yumlog.recipes;
create policy "recipes member delete" on yumlog.recipes
  for delete to authenticated using ((select yumlog.is_member()));

-- ingredients
drop policy if exists "ingredients public read" on yumlog.ingredients;
create policy "ingredients public read" on yumlog.ingredients
  for select to anon, authenticated using (true);
drop policy if exists "ingredients member insert" on yumlog.ingredients;
create policy "ingredients member insert" on yumlog.ingredients
  for insert to authenticated with check ((select yumlog.is_member()));
drop policy if exists "ingredients member update" on yumlog.ingredients;
create policy "ingredients member update" on yumlog.ingredients
  for update to authenticated
  using ((select yumlog.is_member())) with check ((select yumlog.is_member()));
drop policy if exists "ingredients member delete" on yumlog.ingredients;
create policy "ingredients member delete" on yumlog.ingredients
  for delete to authenticated using ((select yumlog.is_member()));

-- recipe_ingredients
drop policy if exists "recipe_ingredients public read" on yumlog.recipe_ingredients;
create policy "recipe_ingredients public read" on yumlog.recipe_ingredients
  for select to anon, authenticated using (true);
drop policy if exists "recipe_ingredients member insert" on yumlog.recipe_ingredients;
create policy "recipe_ingredients member insert" on yumlog.recipe_ingredients
  for insert to authenticated with check ((select yumlog.is_member()));
drop policy if exists "recipe_ingredients member update" on yumlog.recipe_ingredients;
create policy "recipe_ingredients member update" on yumlog.recipe_ingredients
  for update to authenticated
  using ((select yumlog.is_member())) with check ((select yumlog.is_member()));
drop policy if exists "recipe_ingredients member delete" on yumlog.recipe_ingredients;
create policy "recipe_ingredients member delete" on yumlog.recipe_ingredients
  for delete to authenticated using ((select yumlog.is_member()));

-- shopping_list: members only, for everything (anon has no grant at all)
drop policy if exists "shopping_list members only" on yumlog.shopping_list;
create policy "shopping_list members only" on yumlog.shopping_list
  for all to authenticated
  using ((select yumlog.is_member())) with check ((select yumlog.is_member()));

-- members: RLS on (001), deliberately no policies.

notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- Verification (the grid the editor shows). Every row: status = OK.
-- Privilege lists use Postgres names in a fixed order:
-- SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ('-' = none).
-- ---------------------------------------------------------------------------
with
roles(role) as (
  values ('anon'::name), ('authenticated'), ('service_role'), ('public')
),
privs(ord, priv) as (
  values (1, 'SELECT'), (2, 'INSERT'), (3, 'UPDATE'), (4, 'DELETE'),
         (5, 'TRUNCATE'), (6, 'REFERENCES'), (7, 'TRIGGER')
),
tables(tbl) as (
  values ('recipes'), ('ingredients'), ('recipe_ingredients'), ('shopping_list'), ('members')
),
table_expected(tbl, role, privs) as (
  select t.tbl, r.role,
         case
           when r.role = 'anon' and t.tbl in ('recipes', 'ingredients', 'recipe_ingredients') then 'SELECT'
           when r.role = 'authenticated' and t.tbl <> 'members' then 'SELECT,INSERT,UPDATE,DELETE'
           else '-'
         end
  from tables t cross join roles r
),
table_actual(tbl, role, privs) as (
  select t.tbl, r.role,
         coalesce((select string_agg(p.priv, ',' order by p.ord)
                   from privs p
                   where to_regclass('yumlog.' || t.tbl) is not null
                     and has_table_privilege(r.role, to_regclass('yumlog.' || t.tbl), p.priv)), '-')
  from tables t cross join roles r
),
fn_expected(fn, definer, auth_exec) as (
  values
    ('is_member()',                                    'true',  'true'),
    ('merge_ingredients(p_source text, p_target text)', 'false', 'true'),
    ('touch_recipes_for_ingredient(p_ingredient text)', 'false', 'true'),
    ('shopping_list_set_updated_at()',                 'false', 'false'),
    ('request_site_rebuild()',                         'true',  'false')   -- from 003
),
fns as (
  select p.oid, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' as fn,
         p.prosecdef, p.proconfig
  from pg_proc p
  where p.pronamespace = to_regnamespace('yumlog')
),
policies(tbl, pol, cmd, roles, qual, chk) as (
  select tablename::text, policyname::text, cmd::text, array_to_string(roles, ','),
         coalesce(qual, '-'), coalesce(with_check, '-')
  from pg_policies
  where schemaname = 'yumlog'
),
report(ord, item, expected, actual) as (
  select 10, 'schema USAGE ' || r.role,
         case when r.role in ('anon', 'authenticated') then 'true' else 'false' end,
         has_schema_privilege(r.role, 'yumlog', 'USAGE')::text
  from roles r
  union all
  select 11, 'schema CREATE ' || r.role, 'false',
         has_schema_privilege(r.role, 'yumlog', 'CREATE')::text
  from roles r
  union all
  select 20, 'table ' || e.tbl || ' -> ' || e.role, e.privs, a.privs
  from table_expected e
  join table_actual a on a.tbl = e.tbl and a.role = e.role
  union all
  select 30, 'sequence ' || s.seq || ' -> ' || r.role,
         case when r.role = 'authenticated' then 'USAGE,SELECT' else '-' end,
         coalesce(nullif(concat_ws(',',
           case when has_sequence_privilege(r.role, to_regclass('yumlog.' || s.seq), 'USAGE') then 'USAGE' end,
           case when has_sequence_privilege(r.role, to_regclass('yumlog.' || s.seq), 'SELECT') then 'SELECT' end,
           case when has_sequence_privilege(r.role, to_regclass('yumlog.' || s.seq), 'UPDATE') then 'UPDATE' end
         ), ''), '-')
  from (values ('recipe_ingredients_id_seq'), ('shopping_list_id_seq')) as s(seq)
  cross join roles r
  -- every function in the schema, including any not listed in fn_expected
  union all
  select 40, 'fn ' || f.fn || ': security_definer / config',
         coalesce(e.definer, '<unexpected function>') || ' / search_path=""',
         f.prosecdef::text || ' / ' || coalesce(array_to_string(f.proconfig, ','), '<none>')
  from fns f left join fn_expected e on e.fn = f.fn
  union all
  select 41, 'fn ' || f.fn || ': EXECUTE anon/authenticated/service_role/public',
         'false/' || coalesce(e.auth_exec, '<unexpected function>') || '/false/false',
         has_function_privilege('anon', f.oid, 'EXECUTE')::text
         || '/' || has_function_privilege('authenticated', f.oid, 'EXECUTE')::text
         || '/' || has_function_privilege('service_role', f.oid, 'EXECUTE')::text
         || '/' || has_function_privilege('public', f.oid, 'EXECUTE')::text
  from fns f left join fn_expected e on e.fn = f.fn
  union all
  select 42, 'fn ' || e.fn || ' exists', 'true',
         exists (select 1 from fns f where f.fn = e.fn)::text
  from fn_expected e
  where e.fn <> 'request_site_rebuild()'
  union all
  select 50, 'policy count', '13', (select count(*) from policies)::text
  union all
  select 51, 'policy ' || p.tbl || '."' || p.pol || '"',
         case
           when p.pol like '% public read' then 'SELECT to anon,authenticated using true check -'
           when p.pol like '% member insert' then 'INSERT to authenticated using - check (SELECT yumlog.is_member())'
           when p.pol like '% member update' then 'UPDATE to authenticated using (SELECT yumlog.is_member()) check (SELECT yumlog.is_member())'
           when p.pol like '% member delete' then 'DELETE to authenticated using (SELECT yumlog.is_member()) check -'
           when p.pol = 'shopping_list members only' then 'ALL to authenticated using (SELECT yumlog.is_member()) check (SELECT yumlog.is_member())'
           else '<unexpected policy>'
         end,
         -- deparse prints "( SELECT yumlog.is_member() AS is_member)"; normalise
         -- the spacing and alias so the comparison is about meaning, not layout
         regexp_replace(regexp_replace(
           p.cmd || ' to ' || p.roles || ' using ' || p.qual || ' check ' || p.chk,
           '\(\s+', '(', 'g'), ' AS is_member', '', 'g')
  from policies p
  union all
  select 52, 'policies on members', '0',
         (select count(*) from policies where tbl = 'members')::text
  union all
  select 60, 'RLS enabled on all 5 tables', '5',
         (select count(*) from pg_class c
          where c.relnamespace = to_regnamespace('yumlog') and c.relkind = 'r'
            and c.relname in (select tbl from tables) and c.relrowsecurity)::text
)
select ord, item, expected, actual,
       case when expected = actual then 'OK' else 'MISMATCH' end as status
from report
order by ord, item;

$m002$;

  -- ===== supabase/migrations/003_yumlog_rebuild_webhook.sql (verbatim) =====
  execute $m003$
-- =============================================================================
-- 003_yumlog_rebuild_webhook.sql  --  recipes change -> Cloudflare deploy hook
--
-- PURPOSE:    Recipe pages are static, so a change to yumlog.recipes must
--             trigger a rebuild. A statement-level trigger calls
--             request_site_rebuild(), which POSTs to the Cloudflare deploy
--             hook via pg_net. The hook URL lives in Supabase Vault as
--             `yumlog_deploy_hook` and NEVER appears in SQL: function and
--             trigger source is readable by anyone who can call wrapt's
--             public.run_ask_sql (anon included), and the SQL editor keeps
--             query history. Create/edit the secret in the dashboard Vault UI.
--
--             Designed so a rebuild problem can never break a recipe save:
--               * no pg_net installed      -> no-op
--               * no Vault / no secret     -> no-op (this is how the webhook is
--                                             "off" during loads and tests)
--               * caller is an API user who is not a yumlog member -> no-op
--                 (a statement trigger fires even when RLS filters the UPDATE
--                 to 0 rows, so without this any wrapt sign-up could spam
--                 rebuilds with an UPDATE that matches nothing)
--               * anything else fails  -> WARNING, and the save still commits
--             pg_net sends after commit, so a rolled-back transaction (dry run,
--             RLS tests) sends nothing.
--             Statement-level: a merge touching 10 recipes = 1 POST, not 10.
-- RUN IN:     wrapt's Supabase project, after 002. pg_net should be enabled
--             first (Database -> Extensions -> pg_net), but this file does not
--             need it: without pg_net the trigger simply does nothing.
-- IDEMPOTENT: yes (create or replace; drop trigger if exists then create).
-- RESULT:     verification SELECT; rows marked INFO are facts to copy back,
--             not pass/fail. The pg_net rows answer PLAN Q7/R19: if anon or
--             authenticated show EXECUTE = true on net.http_post, run
--             005_optional_revoke_net_http.sql.
-- ROLLBACK:   drop trigger if exists yumlog_rebuild_site on yumlog.recipes;
--             drop function if exists yumlog.request_site_rebuild();
-- =============================================================================

create or replace function yumlog.request_site_rebuild()
returns trigger
language plpgsql
security definer          -- needs to read vault.decrypted_secrets and call net.*
set search_path = ''
as $$
declare
  hook text;
begin
  begin
    -- pg_net not installed: nothing to send with.
    if not exists (select 1 from pg_catalog.pg_extension where extname = 'pg_net') then
      return null;
    end if;

    -- Requests through the Data API carry JWT claims; only members may cause
    -- a rebuild. SQL-editor / dashboard edits carry no claims and always may.
    if coalesce(pg_catalog.current_setting('request.jwt.claims', true), '') <> ''
       and not yumlog.is_member() then
      return null;
    end if;

    if pg_catalog.to_regclass('vault.decrypted_secrets') is null then
      return null;
    end if;

    select s.decrypted_secret into hook
    from vault.decrypted_secrets s
    where s.name = 'yumlog_deploy_hook'
    limit 1;

    -- No secret = webhook off (preview setup, data loads, rollback).
    if hook is null or hook = '' then
      return null;
    end if;

    perform net.http_post(
      url                  := hook,
      body                 := '{}'::jsonb,
      headers              := '{"Content-Type": "application/json"}'::jsonb,
      timeout_milliseconds := 5000
    );
  exception when others then
    -- Never fail the recipe write over a rebuild. SQLSTATE only: the message
    -- could echo the hook URL.
    raise warning 'yumlog_rebuild_site: rebuild request not queued (SQLSTATE %)', sqlstate;
  end;
  return null;
end;
$$;

-- Trigger-only. EXECUTE isn't checked when a trigger fires, so nobody needs it.
revoke execute on function yumlog.request_site_rebuild() from public, anon, authenticated, service_role;

drop trigger if exists yumlog_rebuild_site on yumlog.recipes;
create trigger yumlog_rebuild_site
  after insert or update or delete on yumlog.recipes
  for each statement execute function yumlog.request_site_rebuild();

notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- Verification (the grid the editor shows). status = OK / MISMATCH / INFO.
-- Never selects the secret's value — only whether it exists.
-- ---------------------------------------------------------------------------
with
net_fns as (
  select p.oid, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' as fn
  from pg_proc p
  where p.pronamespace = to_regnamespace('net')
    and p.proname in ('http_post', 'http_get', 'http_delete')
),
report(ord, item, expected, actual) as (
  select 10, 'fn request_site_rebuild: security_definer / config', 'true / search_path=""',
         coalesce((select p.prosecdef::text || ' / ' || coalesce(array_to_string(p.proconfig, ','), '<none>')
                   from pg_proc p where p.oid = to_regprocedure('yumlog.request_site_rebuild()')), '<missing>')
  union all
  select 11, 'fn request_site_rebuild: EXECUTE anon/authenticated/service_role/public', 'false/false/false/false',
         coalesce((select has_function_privilege('anon', p.oid, 'EXECUTE')::text
                          || '/' || has_function_privilege('authenticated', p.oid, 'EXECUTE')::text
                          || '/' || has_function_privilege('service_role', p.oid, 'EXECUTE')::text
                          || '/' || has_function_privilege('public', p.oid, 'EXECUTE')::text
                   from pg_proc p where p.oid = to_regprocedure('yumlog.request_site_rebuild()')), '<missing>')
  union all
  select 12, 'fn request_site_rebuild: source has no URL', 'true',
         coalesce((select (pg_get_functiondef(p.oid) !~* 'https?://')::text
                   from pg_proc p where p.oid = to_regprocedure('yumlog.request_site_rebuild()')), '<missing>')
  union all
  select 20, 'trigger yumlog_rebuild_site', 'enabled AFTER INSERT/UPDATE/DELETE FOR EACH STATEMENT',
         coalesce((select case tg.tgenabled when 'D' then 'disabled' else 'enabled' end
                          || case when (tg.tgtype & 2) <> 0 then ' BEFORE' else ' AFTER' end
                          || ' ' || concat_ws('/',
                               case when (tg.tgtype & 4) <> 0 then 'INSERT' end,
                               case when (tg.tgtype & 16) <> 0 then 'UPDATE' end,
                               case when (tg.tgtype & 8) <> 0 then 'DELETE' end)
                          || case when (tg.tgtype & 1) <> 0 then ' FOR EACH ROW' else ' FOR EACH STATEMENT' end
                   from pg_trigger tg
                   where tg.tgrelid = to_regclass('yumlog.recipes') and tg.tgname = 'yumlog_rebuild_site'), '<missing>')
  union all
  select 21, 'other triggers on yumlog.recipes', '0',
         (select count(*) from pg_trigger tg
          where tg.tgrelid = to_regclass('yumlog.recipes') and not tg.tgisinternal
            and tg.tgname <> 'yumlog_rebuild_site')::text
  -- facts (INFO): copy these back
  union all
  select 30, 'pg_net installed (INFO; needed before the webhook can fire)', 'INFO',
         coalesce((select 'true, version ' || e.extversion || ', schema ' || e.extnamespace::regnamespace::text
                   from pg_extension e where e.extname = 'pg_net'), 'false')
  union all
  select 31, 'Vault secret yumlog_deploy_hook present (INFO; value not shown)', 'INFO',
         -- dynamic (query_to_xml) so this row can't fail at parse time if Vault is absent
         case when to_regclass('vault.secrets') is null then 'vault not installed'
              when not has_table_privilege('vault.secrets', 'SELECT') then 'cannot check (no SELECT on vault.secrets)'
              else (xpath('/row/c/text()', query_to_xml(
                      'select count(*) as c from vault.secrets where name = ''yumlog_deploy_hook''',
                      false, true, '')))[1]::text || ' row(s)' end
  union all
  -- the trigger function runs as its owner, postgres: both must be true for
  -- the webhook to fire at all
  select 32, 'postgres can read vault.decrypted_secrets (INFO; must be true)', 'INFO',
         case when to_regclass('vault.decrypted_secrets') is null then 'vault not installed'
              else has_table_privilege('postgres', 'vault.decrypted_secrets', 'SELECT')::text end
  union all
  select 40, 'net.' || n.fn || ' EXECUTE anon/authenticated/public/postgres (INFO; anon or authenticated true => consider 005; postgres must be true)', 'INFO',
         has_function_privilege('anon', n.oid, 'EXECUTE')::text
         || '/' || has_function_privilege('authenticated', n.oid, 'EXECUTE')::text
         || '/' || has_function_privilege('public', n.oid, 'EXECUTE')::text
         || '/' || has_function_privilege('postgres', n.oid, 'EXECUTE')::text
  from net_fns n
  union all
  select 41, 'schema net USAGE anon/authenticated (INFO)', 'INFO',
         case when to_regnamespace('net') is null then 'schema net absent'
              else has_schema_privilege('anon', 'net', 'USAGE')::text
                   || '/' || has_schema_privilege('authenticated', 'net', 'USAGE')::text end
)
select ord, item, expected, actual,
       case when expected = 'INFO' then 'INFO'
            when expected = actual then 'OK' else 'MISMATCH' end as status
from report
order by ord, item;

$m003$;

  -- ===== supabase/migrations/004_yumlog_realtime.sql (verbatim) =====
  execute $m004$
-- =============================================================================
-- 004_yumlog_realtime.sql  --  live shopping-list sync between devices
--
-- PURPOSE:    Add yumlog.shopping_list to the supabase_realtime publication so
--             subscribeShoppingList() (src/lib/shopping-list.ts) receives
--             postgres_changes events. It never worked in the old project (the
--             table was never in the publication). Realtime checks RLS per
--             subscriber, so only members get row events; anon has no SELECT
--             grant. DELETE events are not RLS-filtered but carry only the
--             primary key (default replica identity), and the client just
--             refetches under RLS.
-- RUN IN:     wrapt's Supabase project, after 002.
-- IDEMPOTENT: yes — the table is only added if it isn't already a member.
-- RESULT:     verification SELECT; every row status = OK.
-- ROLLBACK:   alter publication supabase_realtime drop table yumlog.shopping_list;
-- =============================================================================

do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    raise exception 'publication supabase_realtime not found — is Realtime enabled on this project?';
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'yumlog' and tablename = 'shopping_list'
  ) then
    alter publication supabase_realtime add table yumlog.shopping_list;
  end if;
end
$$;

notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- Verification (the grid the editor shows). Every row: status = OK.
-- ---------------------------------------------------------------------------
with report(ord, item, expected, actual) as (
  select 1, 'yumlog.shopping_list in supabase_realtime', 'true',
         exists (select 1 from pg_publication_tables
                 where pubname = 'supabase_realtime' and schemaname = 'yumlog'
                   and tablename = 'shopping_list')::text
  union all
  select 2, 'other yumlog tables in supabase_realtime', '0',
         (select count(*) from pg_publication_tables
          where pubname = 'supabase_realtime' and schemaname = 'yumlog'
            and tablename <> 'shopping_list')::text
  union all
  select 3, 'authenticated SELECT on yumlog.shopping_list (Realtime needs it)', 'true',
         has_table_privilege('authenticated', 'yumlog.shopping_list', 'SELECT')::text
  union all
  select 4, 'anon SELECT on yumlog.shopping_list', 'false',
         has_table_privilege('anon', 'yumlog.shopping_list', 'SELECT')::text
  union all
  select 5, 'RLS enabled on yumlog.shopping_list', 'true',
         (select c.relrowsecurity from pg_class c where c.oid = 'yumlog.shopping_list'::regclass)::text
)
select ord, item, expected, actual,
       case when expected = actual then 'OK' else 'MISMATCH' end as status
from report
order by ord;

$m004$;

  -- ---------------------------------------------------------------------
  -- Catalogue checks on what the four files just built (still inside the
  -- same transaction). Any problem => DRY RUN FAILED; otherwise DRY RUN OK.
  -- Both are exceptions, so either way nothing is kept.
  -- ---------------------------------------------------------------------
  select count(*) into n from pg_class c
   where c.relnamespace = to_regnamespace('yumlog') and c.relkind = 'r';
  summary := summary || format('tables=%s ', n);
  if n <> 5 then problems := problems || format('expected 5 tables, got %s; ', n); end if;

  select count(*) into n from pg_policies where schemaname = 'yumlog';
  summary := summary || format('policies=%s ', n);
  if n <> 13 then problems := problems || format('expected 13 policies, got %s; ', n); end if;

  select count(*) into n from pg_proc where pronamespace = to_regnamespace('yumlog');
  summary := summary || format('functions=%s ', n);
  if n <> 5 then problems := problems || format('expected 5 functions, got %s; ', n); end if;

  select count(*) into n from pg_trigger tg join pg_class c on c.oid = tg.tgrelid
   where c.relnamespace = to_regnamespace('yumlog') and not tg.tgisinternal;
  summary := summary || format('triggers=%s ', n);
  if n <> 2 then problems := problems || format('expected 2 triggers, got %s; ', n); end if;

  select count(*) into n from pg_index i join pg_class c on c.oid = i.indrelid
   where c.relnamespace = to_regnamespace('yumlog');
  summary := summary || format('indexes=%s ', n);
  if n <> 8 then problems := problems || format('expected 8 indexes (5 pkeys + 3 FK), got %s; ', n); end if;

  if not has_schema_privilege('anon', 'yumlog', 'USAGE') then problems := problems || 'anon lacks schema USAGE; '; end if;
  if has_schema_privilege('service_role', 'yumlog', 'USAGE') then problems := problems || 'service_role HAS schema USAGE; '; end if;
  if not has_table_privilege('anon', 'yumlog.recipes', 'SELECT') then problems := problems || 'anon cannot SELECT recipes; '; end if;
  if has_table_privilege('anon', 'yumlog.shopping_list', 'SELECT') then problems := problems || 'anon CAN SELECT shopping_list; '; end if;
  if has_table_privilege('anon', 'yumlog.recipes', 'INSERT') then problems := problems || 'anon CAN INSERT recipes; '; end if;
  if has_table_privilege('authenticated', 'yumlog.members', 'SELECT') then problems := problems || 'authenticated CAN SELECT members; '; end if;
  if not has_table_privilege('authenticated', 'yumlog.shopping_list', 'DELETE') then problems := problems || 'authenticated cannot DELETE shopping_list; '; end if;
  summary := summary || 'grants=checked ';

  select count(*) into n from pg_proc p
   where p.pronamespace = to_regnamespace('yumlog')
     and (has_function_privilege('anon', p.oid, 'EXECUTE') or has_function_privilege('public', p.oid, 'EXECUTE')
          or has_function_privilege('service_role', p.oid, 'EXECUTE'));
  if n <> 0 then problems := problems || format('%s function(s) executable by anon/public/service_role; ', n); end if;
  select count(*) into n from pg_proc p
   where p.pronamespace = to_regnamespace('yumlog') and has_function_privilege('authenticated', p.oid, 'EXECUTE');
  summary := summary || format('authenticated_exec=%s ', n);
  if n <> 3 then problems := problems || format('expected authenticated EXECUTE on 3 functions, got %s; ', n); end if;

  select string_agg(p.proname, ',' order by p.proname) into t from pg_proc p
   where p.pronamespace = to_regnamespace('yumlog') and p.prosecdef;
  summary := summary || format('definer=%s ', coalesce(t, '-'));
  if t is distinct from 'is_member,request_site_rebuild' then
    problems := problems || format('SECURITY DEFINER set should be is_member,request_site_rebuild, got %s; ', coalesce(t, '-'));
  end if;

  select count(*) into n from pg_proc p
   where p.pronamespace = to_regnamespace('yumlog')
     and coalesce(array_to_string(p.proconfig, ','), '') <> 'search_path=""';
  if n <> 0 then problems := problems || format('%s function(s) without search_path=""; ', n); end if;

  if exists (select 1 from pg_publication_tables
             where pubname = 'supabase_realtime' and schemaname = 'yumlog' and tablename = 'shopping_list') then
    summary := summary || 'realtime=yes ';
  else
    problems := problems || 'shopping_list not in supabase_realtime; ';
  end if;

  summary := summary || format('pg_net=%s', exists (select 1 from pg_extension where extname = 'pg_net'));

  if problems <> '' then
    raise exception 'DRY RUN FAILED (all rolled back): %', problems;
  end if;
  raise exception 'DRY RUN OK (all rolled back): %', summary;
end
$dryrun$;
