-- =============================================================================
-- export_from_old.sql  --  PLAN steps 4.6 / 5.2: copy the data out of the OLD project
--
-- GENERATED by `python migration/stage3/loadgen.py static`.
-- RUN IN:     the OLD yumlog project (ref nrmimftrjulvsgonrlzg). READ-ONLY.
-- OUTPUT:     one grid, 5 rows: ingredients, recipes, recipe_ingredients,
--             shopping_list (row_count, md5, json) and _meta (sequence
--             last_values, TimeZone, export time). The json cell is the whole
--             table as a JSON array; md5 is md5() of exactly that text.
-- SEND BACK:  Export -> CSV (the grid view truncates long cells; the CSV
--             doesn't). Claude runs `loadgen.py load <csv> --target wrapt`,
--             which first re-checks every md5 to catch a truncated CSV.
-- =============================================================================
with
ingredients as (
  select coalesce(jsonb_agg(to_jsonb(t) order by t.name collate "C"), '[]'::jsonb)::text as j
  from public.ingredients t
),
recipes as (
  select coalesce(jsonb_agg(to_jsonb(t) order by t.slug collate "C"), '[]'::jsonb)::text as j
  from public.recipes t
),
recipe_ingredients as (
  select coalesce(jsonb_agg(to_jsonb(t) order by t.id), '[]'::jsonb)::text as j
  from public.recipe_ingredients t
),
shopping_list as (
  select coalesce(jsonb_agg(to_jsonb(t) order by t.id), '[]'::jsonb)::text as j
  from public.shopping_list t
),
meta as (
  select jsonb_build_object(
    'source_schema', 'public',
    'database', current_database(),
    'exported_at', now(),
    'timezone', current_setting('TimeZone'),
    'recipe_ingredients_id_seq', (select jsonb_build_object('last_value', s.last_value, 'is_called', s.is_called)
               from public.recipe_ingredients_id_seq s),
    'shopping_list_id_seq', (select jsonb_build_object('last_value', s.last_value, 'is_called', s.is_called)
               from public.shopping_list_id_seq s)
  )::text as j
)
select 1 as ord, 'ingredients' as tbl, jsonb_array_length(j::jsonb) as row_count, md5(j) as md5, j as json from ingredients
union all
select 2 as ord, 'recipes' as tbl, jsonb_array_length(j::jsonb) as row_count, md5(j) as md5, j as json from recipes
union all
select 3 as ord, 'recipe_ingredients' as tbl, jsonb_array_length(j::jsonb) as row_count, md5(j) as md5, j as json from recipe_ingredients
union all
select 4 as ord, 'shopping_list' as tbl, jsonb_array_length(j::jsonb) as row_count, md5(j) as md5, j as json from shopping_list
union all
select 5, '_meta', null, md5(j), j from meta
order by ord;
