-- =============================================================================
-- checksum.sql  --  PLAN steps 4.6 / 5.5: prove the copy is exact
--
-- GENERATED by `python docs/archive/2026-09-supabase-to-wrapt/stage3/loadgen.py static`.
-- RUN IN:     BOTH projects, read-only. Edit ONE value first:
--               old yumlog project:  'public'
--               wrapt project:       'yumlog'   (as shipped)
-- OUTPUT:     one grid: per table the row count and an md5 over every column of
--             every row, in primary-key order (collation "C"), timestamps in UTC
--             — so neither database's TimeZone nor collation can cause a false
--             mismatch. Then the identity sequences' last_value.
-- MATCH:      row_count and md5 identical per table on both sides. Wrapt's
--             sequences must be >= the old project's (the load sets them to
--             greatest(max id, old last_value)).
-- =============================================================================
with
params(s) as (values ('yumlog'::text)),   -- <== 'public' in the OLD project, 'yumlog' in wrapt
tables(ord, tbl, q) as (
  values
    (1, 'ingredients', $q$select count(*) as n, md5(coalesce(string_agg(jsonb_build_array(t.name, t.category)::text, chr(10) order by t.name collate "C"), '')) as h from %I.ingredients t$q$),
    (2, 'recipes', $q$select count(*) as n, md5(coalesce(string_agg(jsonb_build_array(t.slug, t.title, t.category, t.protein, t.cook_time_min, t.method, t.source_url, t.created_at at time zone 'UTC', t.tips, t.substitutions, t.updated_at at time zone 'UTC')::text, chr(10) order by t.slug collate "C"), '')) as h from %I.recipes t$q$),
    (3, 'recipe_ingredients', $q$select count(*) as n, md5(coalesce(string_agg(jsonb_build_array(t.id, t.recipe_slug, t.ingredient, t.display_name, t.quantity, t.unit)::text, chr(10) order by t.id), '')) as h from %I.recipe_ingredients t$q$),
    (4, 'shopping_list', $q$select count(*) as n, md5(coalesce(string_agg(jsonb_build_array(t.id, t.ingredient, t.quantity, t.unit, t.checked, t.position, t.added_at at time zone 'UTC', t.updated_at at time zone 'UTC')::text, chr(10) order by t.id), '')) as h from %I.shopping_list t$q$)
),
counted as (
  select t.ord, t.tbl, query_to_xml(format(t.q, p.s), false, true, '') as x
  from tables t cross join params p
)
select c.ord, c.tbl as item,
       (xpath('/row/n/text()', c.x))[1]::text as row_count,
       (xpath('/row/h/text()', c.x))[1]::text as md5
from counted c
union all
select 10 + row_number() over (order by s.sequencename), 'sequence ' || s.sequencename,
       coalesce(s.last_value::text, '<never used>'), null
from pg_sequences s cross join params p
where s.schemaname = p.s
  and s.sequencename in ('recipe_ingredients_id_seq', 'shopping_list_id_seq')
union all
select 20, 'schema / database / TimeZone (info)',
       p.s || ' / ' || current_database() || ' / ' || current_setting('TimeZone'), null
from params p
order by 1;
