-- =============================================================================
-- export_from_wrapt.sql  --  ROLLBACK ONLY (PLAN R-B step 3): copy yumlog.* back out
--
-- GENERATED by `python docs/archive/2026-09-supabase-to-wrapt/stage3/loadgen.py static`.
-- RUN IN:     wrapt's project. READ-ONLY. Same output shape as export_from_old.sql.
-- USE:        only if cutover is rolled back after writes landed in wrapt.
--             Export -> CSV, then `loadgen.py load <csv> --target old` builds
--             the reverse-sync chunks + swap for the OLD project.
-- =============================================================================
with
ingredients as (
  select coalesce(jsonb_agg(to_jsonb(t) order by t.name collate "C"), '[]'::jsonb)::text as j
  from yumlog.ingredients t
),
recipes as (
  select coalesce(jsonb_agg(to_jsonb(t) order by t.slug collate "C"), '[]'::jsonb)::text as j
  from yumlog.recipes t
),
recipe_ingredients as (
  select coalesce(jsonb_agg(to_jsonb(t) order by t.id), '[]'::jsonb)::text as j
  from yumlog.recipe_ingredients t
),
shopping_list as (
  select coalesce(jsonb_agg(to_jsonb(t) order by t.id), '[]'::jsonb)::text as j
  from yumlog.shopping_list t
),
meta as (
  select jsonb_build_object(
    'source_schema', 'yumlog',
    'database', current_database(),
    'exported_at', now(),
    'timezone', current_setting('TimeZone'),
    'recipe_ingredients_id_seq', (select jsonb_build_object('last_value', s.last_value, 'is_called', s.is_called)
               from yumlog.recipe_ingredients_id_seq s),
    'shopping_list_id_seq', (select jsonb_build_object('last_value', s.last_value, 'is_called', s.is_called)
               from yumlog.shopping_list_id_seq s)
  )::text as j
)
select 1 as ord, 'ingredients' as tbl, jsonb_array_length(j::jsonb) as row_count, md5(j) as md5, j as json from ingredients
union all
select 2 as ord, 'recipes' as tbl, jsonb_array_length(j::jsonb) as row_count, md5(j) as md5, j as json from recipes
union all
select 3 as ord, 'recipe_ingredients' as tbl, jsonb_array_length(j::jsonb) as row_count, md5(j) as md5, j as json from recipe_ingredients
union all
select 4 as ord, 'shopping_list' as tbl, jsonb_array_length(j::jsonb) as row_count, md5(j) as md5, j as json from shopping_list
union all
select 5, '_meta', null, md5(j), j from meta
order by ord;
